unique_ids:
  assets:
    standard-page.html: SWEATGKQGCICMXZ4FOXKBPEXE3CLMBVD
    theme.css: U2OW2H2D47SPLRAF52C73OE7S4HF5LCL
  forms:
    Form1: X7R6QRDQX5IQE6OAFMUWY5IUWUPMYKJR
  modules: {}
  scripts: {}
  server_modules: {}
